export enum Type {
    ABERRATION = 'aberration',
    ANIMAL = 'animal',
    CELESTIAL = 'celestial',
    CONSTRUCT = 'construct',
    DRAGON = 'dragon',
    ELEMENTAL = 'elemental',
    FEY = 'fey',
    FIEND = 'fiend',
    GIANT = 'giant',
    HUMANOID = 'humanoid',
    MAGICAL_BEAST = 'magical beast',
    MONSTROUS_HUMANOID = 'monstrous humanoid',
    MONSTROSITY = 'monstrosity',
    OOZE = 'ooze',
    OUTSIDER = 'outsider',
    PLANT = 'plant',
    UNDEAD = 'undead',
    VERMIN = 'vermin',
}
